# DataFrame
- 행열을 가진 2차원 자료구조
- 여러개의 Series 묶음 자료형

In [55]:
import numpy as np
import pandas as pd

## DataFrame 생성

In [56]:
# dict -> df 생성
data = {"one": [1.0, 2.0, 3.0], "two": [10, 20, 30], "three": 99}

# dict의 각 item(key:value)이 하나의 Series로 처리됨
df = pd.DataFrame(data)
print(df["one"])    # "one" 열의 Series 선택
df  # broadcasting

0    1.0
1    2.0
2    3.0
Name: one, dtype: float64

   one  two  three
0  1.0   10     99
1  2.0   20     99
2  3.0   30     99

In [57]:
# 여러 개의 dict -> dataframe
data: list[dict[str, int]] = [{
    "a": 10,
    "b": 20,
}, {
    "a": 30,
    "b": 40,
    "c": 50,
}]

# 하나의 dict -> 하나의 레코드, key는 컬럼으로 처리
df = pd.DataFrame(data)
df  # NaN == 결측치

    a   b     c
0  10  20   NaN
1  30  40  50.0

In [58]:
# ndarray -> df
arr = np.arange(9).reshape(3, 3)
df = pd.DataFrame(arr, columns = ("a", "b", "c"), index=['1일', '2일', '3일'])
df

    a  b  c
1일  0  1  2
2일  3  4  5
3일  6  7  8

In [59]:
# ser -> df
name_ser = pd.Series(['홍길동', '이순신', '강감찬'])
age_ser = pd.Series([20, 25, 30])
df = pd.DataFrame({"name": name_ser, "age": age_ser})
df

  name  age
0  홍길동   20
1  이순신   25
2  강감찬   30

In [60]:
# tuple(record) -> dataframe
# 하나의 객체

data = [
    ('홍길동', 20),
    ('이순신', 30),
    ('논개', 43),
]
df = pd.DataFrame.from_records(data, columns=['이름', '나이'])
df

    이름  나이
0  홍길동  20
1  이순신  30
2   논개  43

## DataFrame 속성

In [61]:
data = {
    'Bank client ID':[1, 2, 3, 4],
    'Bank Client Name':['Laila Aly', 'Kate Steve', 'Nicole Mitch', 'Francis Morris'],
    'Net worth [$]':[35000, 3000, 100000, 2000],
    'Years with bank':[4, 7, 10, 15]
}
df = pd.DataFrame(data)
df

   Bank client ID Bank Client Name  Net worth [$]  Years with bank
0               1        Laila Aly          35000                4
1               2       Kate Steve           3000                7
2               3     Nicole Mitch         100000               10
3               4   Francis Morris           2000               15

In [62]:
df.info()  # df 정보
# RangeIndex: 4 entries

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Bank client ID    4 non-null      int64
 1   Bank Client Name  4 non-null      str
 2   Net worth [$]     4 non-null      int64
 3   Years with bank   4 non-null      int64
dtypes: int64(3), str(1)
memory usage: 305.0 bytes

In [63]:
df.describe()

       Bank client ID  Net worth [$]  Years with bank
count        4.000000       4.000000         4.000000
mean         2.500000   35000.000000         9.000000
std          1.290994   45963.753836         4.690416
min          1.000000    2000.000000         4.000000
25%          1.750000    2750.000000         6.250000
50%          2.500000   19000.000000         8.500000
75%          3.250000   51250.000000        11.250000
max          4.000000  100000.000000        15.000000

In [64]:
print(df.rowsb)
print(df.columns)

AttributeError: 'DataFrame' object has no attribute 'rowsb'

In [ ]:
print(df.dtypes)
print(df.shape)
print(df.size)

## DataFrame 메서드

In [ ]:
# head(n), tail(n):  맨 위, 맨 마지막 n개 조회
display(df.head(2))
display(df.tail(2))

In [ ]:
# values_counts(): 유일값 분포 확인
df['Years with bank'].value_counts()

In [ ]:
# index 재지정: 특정 컬럼을 index로 지정
df = df.set_index("Bank client ID")
df

## 조회
- 행열조회
    - df.iloc[인덱스]
    - df.loc[라벨]
- 열조회
    - df[컬럼명]

### iloc (인덱스 위치)

In [ ]:
dicts = [
    {'name' : '홍길동', 'job' : '강사', 'age' : 33},
    {'name' : '신사임당', 'age' : 44, 'job' : '영업사원'},
    {'name' : '이순신', 'age' : 38, 'job' : '장군'},
    {'name' : '논개', 'age' : 25, 'job' : '개발'},
    {'name' : '강감찬', 'age' : 47, 'job' : '교수'},
]
df = pd.DataFrame(dicts)
df

In [ ]:
# 홍길동 행 조회
print(df.iloc[0])
print(type(df.iloc[0])) # type == Series, df에서 한 행 또는 한 열을 Series 타입이다.
print(df.iloc[0].index)
print(df.iloc[0].name)  # fd의 인덱스  == ser의 이름

In [ ]:
# 슬라이싱 지원
df2 = df.iloc[0:2]  # 0, 1행 반환  (2차원) -> df 반환
print(type(df2))
print(df2)

In [ ]:
# fancy indexing 지원
df.iloc[[0, 2]] # 0번 행, 2번 행ㅠ

In [ ]:
# 단일 값 조회
print(df.iloc[0, 1])    # 인덱스 기반이므로 ['job'] X

# 여러 행 조회
df.iloc[:2, 1]

In [ ]:
df2 = df.iloc[:2, :2]
print(type(df2))
df2

### loc
인데스라벨을 통해 조회

In [ ]:
# index명 지정 == 라벨링(labeling)
df.index = ['client1', 'client2', 'client3', 'client4', 'client5']
df

In [ ]:
print(type(df.loc['client4']))
df.loc['client4']

In [ ]:
df.iloc[3]

# df.loc[3]   # 그냥 loc는 인덱스

# loc 슬라이싱은 end 값을 포함한다!

In [ ]:
# loc를 이용한 컬럼 단일 값 조회
df.loc['client3', 'job']

# df.iloc[0, 1]

# loc를 이용한 슬라이싱
print(df.loc['client2': 'client4']) # client4 포함

In [ ]:
# loc를 이용한 슬라이싱 + 컬럼 선택
print(df.loc['client2':'client4', 'job'])

print(df.loc['client2':'client4', 'job':])

### 컬럼라벨

In [ ]:
# df['컬럼명'] : 해당 컬럼 시리즈 반환
df['job']
print(type(df['name']))
df['name']

In [ ]:
# 컬럼 라벨 fancy indexing
print(type(df[['name', 'job']]))
df[['name', 'job']]

In [ ]:
# loc # 레이블 이름으로 선택하는 것
# loc + 컴럼 라벨
print(df['name'] == '이순신')
print('-----------------------------')
print(df.loc[df['name'] == '이순신'])

In [ ]:
# boolean indexing (비교 연산)
print(df['age'] > 30)
df[df['age'] > 30]

In [ ]:
# 30세 미만, 개발 직종을 갖는 행 조회
df.loc[(df['age'] < 30) & (df['job'] == '개발')]

In [ ]:
# - 이름에 '신'이 들어가거나 나이가 40대이상 조회 (OR 연산)
df[(df['age'] >= 40) | (df['name'].str.contains('신'))]

## 행 추가/삭제

In [ ]:
students = [
    {'name': '홍길동', 'midterm': 95, 'final': 85},
    {'name': '신사임당', 'midterm': 85, 'final': 80},
    {'name': '이순신', 'midterm': 10, 'final': 30}
]
df = pd.DataFrame(students)
df

In [ ]:
# 중복되지 않는 인덱스에 한 행(Series 타입) 추가 (대입)
next_index = len(df)
next_index  # 다음 인덱스를 찾을 수 있음

df.loc[next_index] = pd.Series({'name': '강감찬', 'midterm': 88})  # df.loc[3]
# 추가된 행에 final 컬럼값 누락 -> NaN (결측치)
df

In [ ]:
# 중복된 인덱스에 한 행(Series 타입) 대입 -> 수정 (덮어쓰기)
next_index = 3
df.loc[next_index] = pd.Series({'name': '율곡이이', 'midterm': 66})
df

In [ ]:
# 행 삭제 -> 원본 유지
# display(df.drop(3))
# display(df)

df = df.drop(3)
# 원본이 필요없을 때

In [ ]:
# 특정 조건을 만족하는 모든 행 삭제
df = df[df['final'] >= 60]
df

## 컬럼 추가/삭제

In [ ]:
df['phone'] = ['010-1234-1234', '010-3345-3345']
df

In [ ]:
# 중간고사,
df.loc[:, 'mean'] = (df['midterm'] + df['final']) / 2
df

In [ ]:
# 컬럼 삭제
df = df[['name', 'midterm', 'final']]    # fancy indexing 내가 선택한 컬럼만 보기
df
# 덮어씌워서 지우기

In [ ]:
df.loc[2] = {'name': '이순신', 'midterm': 10, 'final': 30}

In [ ]:
# ser|df.apply(함수)
# - 데이터프레임 또는 시리즈 객체의 각 요소에 함수를 적용할 때 사용
# - 데이터 전처리 시 자주 사용
def pass_or_fail(value):
    return 'P' if value >= 60 else 'F'

df.loc[:, 'avg'] = (df['midterm'] + df['final']) / 2
df.loc[:, 'pass_fail'] = df['avg'].apply(pass_or_fail)

df

In [ ]:
# apply 함수에 행(record) 전체를 인자로 전달해서 처리하기
def pass_or_fail2(record):
    avg = record['midterm'] + record['final'] / 2
    return 'P' if avg >= 60 else 'F'

df.loc[:, 'pass_fail2'] = df.apply(pass_or_fail2, axis=1)

## 정렬

In [66]:
#  csv 를 읽어와 df 생성
df = pd.read_csv('./data/bank_client_information.csv')
df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [67]:
df.sort_values('Net Worth', ascending=False)

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1

In [68]:
# 메인 정렬 중 같은 값이 존재하면 추가로 정렬 지정
df.sort_values(['Net Worth', 'Years with Bank'], ascending=[True, False])
df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [69]:
# 순위 부여하기
df.loc[:, 'Net Worth Rank'] = df['Net Worth'].rank(ascending=False).astype(int)
df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Net Worth Rank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5,8
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6,5
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7,6
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10,4
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22,8
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26,1
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11,2
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1,10
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13,7